name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=yes ubuntu@3.124.59.221 << 'EOF'
            cd ~/DeepFakeV2  # CHANGE TO YOUR PROJECT DIR
            git fetch origin main
            git reset --hard origin/main
            docker-compose down
            docker-compose up -d --build
          EOF
